FROM alpine:3.8

LABEL maintainer="Zuo-Wei Wang <kirk.w.wang@gmail.com>" \
  org.label-schema.name="Demo API" \
  org.label-schema.vendor="Zuo-Wei Wang" \
  org.label-schema.schema-version="1.0"

RUN apk add --no-cache ca-certificates && \
  rm -rf /var/cache/apk/*

ADD release/linux/amd64/helloworld /bin/

ENTRYPOINT ["/bin/helloworld"]
